import { ExperienceItem } from '@/types';

export const experienceItems: ExperienceItem[] = [
  {
    logo: '/images/uzca-logo.jpg',
    year: '2025',
    role: 'Director of the Department for the U.S Cooperation and Creative Projects',
    date: 'Nov 2025 – Present',
    location: 'Washington DC · Remote',
    type: 'Part-time',
    org: 'Uzbekistan Creative Association',
    bullets: [
      'Lead projects for U.S. cooperation and creative initiatives.',
      'Oversee partnerships and collaborations for creative projects.',
    ],
    active: true,
  },
  {
    logo: '/images/cndls-logo.jpg',
    year: '2024',
    role: 'Graduate Learning Designer',
    date: 'Aug 2024 – Present',
    location: 'Washington, DC · On-site',
    type: 'Part-time',
    org: 'Center for New Designs in Learning and Scholarship',
    bullets: [
      'Hands-on experience as a team member, collaborating closely with subject matter experts to develop undergraduate, professional level and online learning experiences for Georgetown University.',
      'Create engaging learning activities and engaging course content.',
      'Building courses in Canvas.',
      'Conducting the Quality Assurance (QA) process to ensure course functionality, visual and structural consistency, accessibility compliance, and alignment with established design and instructional standards.',
    ],
    active: true,
  },
  {
    logo: '/images/gu-logo.jpg',
    year: '2025',
    role: 'Graduate Teaching Assistant',
    date: 'Jan 2025 – May 2025',
    location: 'Washington, DC · Remote',
    type: 'Part-time',
    org: 'Georgetown University School of Continuing Studies',
    bullets: [
      'Teaching Assistant of Multimedia Design for Communications undergraduate course.',
      'Supported course materials, student assessments, and project guidance.',
    ],
    active: false,
  },
  {
    logo: '/images/unicon-logo.jpg',
    year: '2023',
    role: 'IT Education and International Relations Grant Manager',
    date: 'Nov 2023 – Aug 2024',
    location: 'Tashkent, Uzbekistan · On-site',
    type: 'Full-time',
    org: 'Unicon Soft',
    bullets: [
      'Managed IT education grants and international collaborations.',
      'Coordinated project reporting and partner communication.',
    ],
    active: false,
  },
  {
    logo: '/images/polito-logo.jpg',
    year: '2023',
    role: 'Lecturer',
    date: 'Sep 2023 – Mar 2024',
    location: 'Tashkent, Uzbekistan · On-site',
    type: 'Part-time',
    org: 'Turin Polytechnic University in Tashkent',
    bullets: [
      'Teaching Building, Planning and Design I and BIM.',
      'Prepared instructional materials and facilitated practical labs.',
    ],
    active: false,
  },
  {
    logo: '/images/innosolver-logo.jpg',
    year: '2021',
    role: 'Head of Department for Development of STEAM Education',
    date: 'Apr 2021 – Nov 2023',
    location: 'Toshkent, Uzbekistan',
    type: 'Full-time',
    org: 'INNO SOLVER',
    bullets: [
      'Prepared an analytic paper and presentation of the prospective investment project with $100 million ADB financing on STEM development for grades 5-11 in public schools.',
      'Participated in the initial feasibility study and provided technical support to ADB experts in data collection regarding school infrastructure, teachers’ competencies, and 200 schools’ selection criteria.',
      'Support on the design, set up and launch of the online survey to collect reports from public schools, including communication with all partners involved.',
      'Developed a science lab layout for STEM, prepared technical drawings, necessary equipment lists, and organized reopening of the renovated school № 286 in Mirzo-Ulugbek District.',
      'Prepared the design project for the first STEM school, oversaw construction and opening of STEM school № 45 Kuyichirchik District with modern science laboratory and robotics sets.',
      'Executed EdTechUz: “Empowering Education through Technology for Teachers” project with Fulbright Specialist Program and American Embassy.',
      'Developed training materials including a methodological manual on educational technologies and pedagogical skills.',
      'Conducted three offline and online EdTech seminars for mentors with 300+ total participants.',
    ],
    active: false,
  },
  {
    logo: '/images/innosolver-logo.jpg',
    year: '2020',
    role: 'Chief Specialist',
    date: 'Dec 2020 – May 2021',
    location: 'Tashkent, Uzbekistan',
    type: 'Full-time',
    org: 'INNO SOLVER',
    bullets: [
      'Headed “I am a STEAM Leader” project including development of training methodology, manuals for chemistry, physics, and biology lab work.',
      'Created video instructional materials for STEM subjects (grades 7-11).',
      'Trained 120 STEAM Leader teachers from 12 regions who continued mentoring other teachers.',
      'Piloted the State project “Development of 28 STEAM Schools” including leadership training for school principals and teacher retraining.',
      'Created methodological manuals for Science grades 1-3 and renovation of STEAM laboratories.',
    ],
    active: false,
  },
  {
    logo: '/images/fielding-logo.jpg',
    year: '2020',
    role: 'Architectural Designer',
    date: 'Jan 2020 – Sep 2020',
    location: 'Providence, Rhode Island Area',
    type: 'Full-time',
    org: 'Fielding International',
    bullets: [
      'Developed redesign concept proposals for K-12 international school projects.',
      'Created Revit models and designed school spaces according to safety regulations.',
    ],
    active: false,
  },
  {
    logo: '/images/fielding-logo.jpg',
    year: '2019',
    role: 'Architectural Designer Intern',
    date: 'May 2019 – Aug 2019',
    location: 'Rhode Island, USA',
    type: 'Full-time',
    org: 'Fielding International',
    bullets: [
      'Developed redesign concept proposals for international K-12 school projects including American School in Israel and Anglo-American School in Moscow.',
      'Worked on planning, graphic representation, furniture and fixtures selection, and Revit modeling for a new library building proposal following Russian fire safety regulations.',
    ],
    active: false,
  },
  {
    logo: '/images/no-logo.jpg',
    year: '2014',
    role: 'Founder, Architect, Designer',
    date: 'May 2014 – 2019',
    location: 'Tashkent, Milan',
    type: 'Full-time',
    org: 'Dezine.Work Studio',
    bullets: [
      'Provided services in space planning, educational programming, specifications for construction, lighting design, project management, and 3D visualizations.',
      'Designed custom furniture, selected finishes and accessories, and delivered complete turn‑key interior design services for individual and corporate clients.',
    ],
    active: false,
  },
  {
    logo: '/images/no-logo.jpg',
    year: '2015',
    role: 'Interior Design Consultant',
    date: 'Apr 2015 – Jan 2017',
    location: 'Tbilisi',
    type: 'Full-time',
    org: 'Synergy Capital',
    bullets: [
      'Actively participated in setting real estate fund strategy and benchmarked properties, locations, and interior design.',
      'Defined and presented fund strategy to investors and collaborated with advisors, property managers, architects, and designers.',
    ],
    active: false,
  },
  {
    logo: '/images/no-logo.jpg',
    year: '2013',
    role: 'Architect / Designer',
    date: 'Jan 2013 – 2014',
    location: 'Milan',
    type: 'Full-time',
    org: 'Studio Argot',
    bullets: [
      'Designed architectural projects and interior spaces.',
      'Prepared technical documentation and design proposals.',
    ],
    active: false,
  },
];
